
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mausvzbzorurkcoruhev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hdXN2emJ6b3J1cmtjb3J1aGV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNDg4MDUsImV4cCI6MjA1OTcyNDgwNX0.6TbKdLzu-elFLxNGqqH8kDL9GCzfc6_ZLMTiqyeoj3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Export commonly used types
export type HandleType = Database['public']['Tables']['handles']['Row'];
export type HistoryType = Database['public']['Tables']['handle_history']['Row'];
export type PlanType = Database['public']['Tables']['plans']['Row'];
export type SubscriptionType = Database['public']['Tables']['subscriptions']['Row'];
